### ISSUE TITLE
AssemblyScript CDK

### ISSUE THREAD

**Issue by rubenhorne** [rubenhorne/ic-issues#35]

**Comment by lastmjs** [comment]
There has been some work done on an AssemblyScript CDK  by @rckprtr.

GitHub repo: https://github.com/rckprtr/cdk-as
DFINITY Forum: https://forum.dfinity.org/t/assemblyscript-cdk-on-dfinity/1592

**Comment by lastmjs** [comment]
We've built a TypeScript/JavaScript CDK that I believe fulfills the desire for an AssemblyScript CDK: https://github.com/demergent-labs/azle
